import type { FeedPost, LiveEvent } from "@/lib/feed/types";

export function fallbackEvents(now = Date.now()): LiveEvent[] {
  return [
    {
      id: "convention-live",
      title: "FOBC Annual Convention 2026",
      details: "Streaming Live",
      streamUrl: "https://www.youtube.com",
      startsAt: new Date(now - 60 * 60 * 1000).toISOString(),
      endsAt: new Date(now + 3 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: "evening-impartation",
      title: "Evening Impartation",
      details: "Upcoming session",
      streamUrl: "https://www.youtube.com",
      startsAt: new Date(now + 26 * 60 * 60 * 1000).toISOString(),
      endsAt: new Date(now + 28 * 60 * 60 * 1000).toISOString(),
    },
  ];
}

export function fallbackPosts(now = Date.now()): FeedPost[] {
  return [
    {
      id: "preview-testimony",
      userId: "preview-amina",
      fullName: "Amina N.",
      avatarUrl: null,
      createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      category: "testimony",
      content:
        "I came to the convention heavy, and left knowing I am not alone. The worship tonight felt like a room full of family.",
      mediaUrl: null,
      mediaType: null,
      tags: ["Gratitude", "Worship"],
      amenCount: 24,
      commentCount: 3,
      prayerCount: 6,
      likedByMe: false,
      prayedByMe: false,
      source: "preview",
      pinned: false,
      featured: false,
      location: null,
      songTitle: null,
      songArtist: null,
      songUrl: null,
      audioUrl: null,
    },
    {
      id: "preview-prayer",
      userId: "preview-joseph",
      fullName: "Joseph K.",
      avatarUrl: null,
      createdAt: new Date(now - 35 * 60 * 1000).toISOString(),
      category: "prayer_request",
      content: "Please pray for my mother as she travels to the evening session. Ask for peace on the road and strength when she arrives.",
      mediaUrl: null,
      mediaType: null,
      tags: ["Family", "Faith"],
      amenCount: 11,
      commentCount: 1,
      prayerCount: 18,
      likedByMe: false,
      prayedByMe: false,
      source: "preview",
      pinned: false,
      featured: false,
      location: null,
      songTitle: null,
      songArtist: null,
      songUrl: null,
      audioUrl: null,
    },
    {
      id: "preview-sermon",
      userId: "preview-grace",
      fullName: "Grace M.",
      avatarUrl: null,
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
      category: "sermon_note",
      content: "Sermon note: blessing is not a performance. It is staying in the room long enough to receive what God already prepared.",
      mediaUrl: null,
      mediaType: null,
      tags: ["Convention", "Faith"],
      amenCount: 41,
      commentCount: 5,
      prayerCount: 2,
      likedByMe: false,
      prayedByMe: false,
      source: "preview",
      pinned: false,
      featured: false,
      location: null,
      songTitle: null,
      songArtist: null,
      songUrl: null,
      audioUrl: null,
    },
    {
      id: "preview-general",
      userId: "preview-samuel",
      fullName: "Samuel T.",
      avatarUrl: null,
      createdAt: new Date(now - 26 * 60 * 60 * 1000).toISOString(),
      category: "general",
      content: "First time at Festival of Blessings. If you are new, the prayer wall is the kindest corner of the app. Say hello.",
      mediaUrl: null,
      mediaType: null,
      tags: ["Convention"],
      amenCount: 15,
      commentCount: 2,
      prayerCount: 0,
      likedByMe: false,
      prayedByMe: false,
      source: "preview",
      pinned: false,
      featured: false,
      location: null,
      songTitle: null,
      songArtist: null,
      songUrl: null,
      audioUrl: null,
    },
  ];
}
